
lcd:	lcd.c ../openvg/libshapes.o ../openvg/oglinit.o
	gcc   -Wall -I../openvg -I/opt/vc/include -I/opt/vc/include/interface/vcos/pthreads -I.. -o lcd lcd.c ../openvg/libshapes.o ../openvg/oglinit.o -L/opt/vc/lib -lGLESv2 -lEGL -lbcm_host -ljpeg -lm
	